/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tommysitu' at '31/05/17 14:28' with Gradle 3.1
 *
 * @author tommysitu, @date 31/05/17 14:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
